name = "ProCGroups"
version = "3.0.0"
defaultTargets = ["ProCGroups"]
enableArtifactCache = false
restoreAllArtifacts = false

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "6f1ef4e5dd604a435bddba4747b13970cd65d2a1"

[[lean_lib]]
name = "ProCGroups"
srcDir = "Lean4"
globs = ["ProCGroups.*"]
leanOptions = {linter.missingDocs = true}
