name = "ProCGroups"
version = "2.0.0"
defaultTargets = ["ProCGroups"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.1"

[[lean_lib]]
name = "ProCGroups"
srcDir = "Lean4"
globs = ["ProCGroups.*"]
leanOptions = {linter.missingDocs = true}
