name = "ProCGroups"
version = "3.0.0"
defaultTargets = ["ProCGroups.All"]
enableArtifactCache = false
restoreAllArtifacts = false

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "5ed2965256430c3649e86755f9576b54eca72435"

[[lean_lib]]
name = "ProCGroups.All"
srcDir = "Lean4"
globs = ["ProCGroups.+"]
leanOptions = {linter.missingDocs = true}
