import Mathlib.Algebra.Group.Subgroup.Basic
import Mathlib.Algebra.BigOperators.Group.List.Basic
import Mathlib.Data.Finset.Sort
import Mathlib.GroupTheory.FreeGroup.Reduce
import Mathlib.GroupTheory.QuotientGroup.Defs

/-!
# Relator equivalence

This module defines equality modulo a relator normal closure and proves its
elementary equivalence, congruence, inversion, multiplication, and quotient
characterizations.
-/

namespace ReidemeisterSchreier.Discrete.Presentations

variable {G H : Type*} [Group G] [Group H]

/-- Equality modulo the normal closure generated by R. -/
def RelatorEquivalent (R : Set G) (u v : G) : Prop :=
  u * v⁻¹ ∈ Subgroup.normalClosure R

/-- Relator equivalence is equivalent to equality in the presented quotient. -/
theorem relatorEquivalent_iff_eq_in_presentedQuotient {R : Set G} {u v : G} :
    RelatorEquivalent R u v ↔
      ((u : G ⧸ Subgroup.normalClosure R) =
        (v : G ⧸ Subgroup.normalClosure R)) := by
  simpa [RelatorEquivalent, div_eq_mul_inv] using
    (QuotientGroup.eq_iff_div_mem
      (N := Subgroup.normalClosure R) (x := u) (y := v)).symm

/-- Relator equivalence to one on the right is membership in the relator normal closure. -/
@[simp] theorem relatorEquivalent_one_right {R : Set G} {u : G} :
    RelatorEquivalent R u 1 ↔ u ∈ Subgroup.normalClosure R := by
  simp only [RelatorEquivalent, inv_one, mul_one]

/-- Relator equivalence from one on the left is membership in the relator normal closure. -/
@[simp] theorem relatorEquivalent_one_left {R : Set G} {u : G} :
    RelatorEquivalent R 1 u ↔ u ∈ Subgroup.normalClosure R := by
  constructor
  · intro h
    have huInv : u⁻¹ ∈ Subgroup.normalClosure R := by
      simpa [RelatorEquivalent] using h
    simpa using Subgroup.inv_mem (Subgroup.normalClosure R) huInv
  · intro h
    have huInv : u⁻¹ ∈ Subgroup.normalClosure R :=
      Subgroup.inv_mem (Subgroup.normalClosure R) h
    simpa [RelatorEquivalent] using huInv

/-- Relator equivalence defines a setoid on the free group. -/
def relatorEquivalentSetoid (R : Set G) : Setoid G where
  r := RelatorEquivalent R
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro u
      rw [relatorEquivalent_iff_eq_in_presentedQuotient]
    · intro u v h
      rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h ⊢
      exact h.symm
    · intro u v w huv hvw
      rw [relatorEquivalent_iff_eq_in_presentedQuotient] at huv hvw ⊢
      exact huv.trans hvw

namespace RelatorEquivalent

variable {R S : Set G} {u v w a b r : G}

/-- Relator equivalence is reflexive. -/
@[refl]
theorem refl (R : Set G) (u : G) : RelatorEquivalent R u u := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient]

/-- Equal relators are relator-equivalent. -/
theorem of_eq (h : u = v) : RelatorEquivalent R u v := by
  rw [h]

/-- Relator equivalence is symmetric. -/
theorem symm (h : RelatorEquivalent R u v) : RelatorEquivalent R v u := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h ⊢
  exact h.symm

/-- Relator equivalence is transitive. -/
theorem trans (h₁ : RelatorEquivalent R u v) (h₂ : RelatorEquivalent R v w) : RelatorEquivalent
    R u w := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h₁ h₂ ⊢
  exact h₁.trans h₂

/-- Taking inverses preserves relator equivalence. -/
theorem inv (h : RelatorEquivalent R u v) : RelatorEquivalent R u⁻¹ v⁻¹ := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h ⊢
  simpa using congrArg Inv.inv h

/-- Multiplication of relator-equivalent words preserves relator equivalence. -/
theorem mul (h₁ : RelatorEquivalent R u v) (h₂ : RelatorEquivalent R a b) :
    RelatorEquivalent R (u * a) (v * b) := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h₁ h₂ ⊢
  calc
    ((u * a : G) : G ⧸ Subgroup.normalClosure R) =
        (u : G ⧸ Subgroup.normalClosure R) * (a : G ⧸ Subgroup.normalClosure R) := rfl
    _ = (v : G ⧸ Subgroup.normalClosure R) * (b : G ⧸ Subgroup.normalClosure R) := by
      rw [h₁, h₂]
    _ = ((v * b : G) : G ⧸ Subgroup.normalClosure R) := rfl

/-- Taking natural powers preserves relator equivalence. -/
theorem pow (h : RelatorEquivalent R u v) (n : ℕ) : RelatorEquivalent R (u ^ n) (v ^ n) := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h ⊢
  simpa using congrArg (fun z : G ⧸ Subgroup.normalClosure R => z ^ n) h

/-- Taking integer powers preserves relator equivalence. -/
theorem zpow (h : RelatorEquivalent R u v) (n : ℤ) : RelatorEquivalent R (u ^ n) (v ^ n) := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h ⊢
  simpa using congrArg (fun z : G ⧸ Subgroup.normalClosure R => z ^ n) h

/-- A product of words relator-equivalent to one is relator-equivalent to one. -/
theorem mul_eq_one (h₁ : RelatorEquivalent R u 1) (h₂ : RelatorEquivalent R v 1) :
    RelatorEquivalent R (u * v) 1 := by
  simpa using mul h₁ h₂

/--
A natural-number power is relator-equivalent to the identity when the base word is
relator-equivalent to the identity.
-/
theorem pow_eq_one (h : RelatorEquivalent R u 1) (n : ℕ) :
    RelatorEquivalent R (u ^ n) 1 := by
  simpa using pow h n

/--
An integer power is relator-equivalent to the identity when the base word is relator-equivalent
to the identity.
-/
theorem zpow_eq_one (h : RelatorEquivalent R u 1) (n : ℤ) :
    RelatorEquivalent R (u ^ n) 1 := by
  simpa using zpow h n

/-- The inverse of a word is relator-equivalent to one exactly when the word is. -/
theorem inv_eq_one (h : RelatorEquivalent R u 1) :
    RelatorEquivalent R u⁻¹ 1 := by
  simpa using inv h

/-- Conjugating a power relator gives an equivalent relator. -/
theorem conjugate_pow_eq (a u : G) (n : ℕ) :
    (a * u * a⁻¹) ^ n = a * u ^ n * a⁻¹ := by
  induction n with
  | zero =>
      simp only [pow_zero, mul_one, mul_inv_cancel]
  | succ n ih =>
      calc
        (a * u * a⁻¹) ^ (n + 1) =
            a * u ^ n * a⁻¹ * (a * u * a⁻¹) := by
              rw [pow_succ, ih]
        _ = a * (u ^ n * u) * a⁻¹ := by
              simp only [mul_assoc, inv_mul_cancel_left]
        _ = a * u ^ (n + 1) * a⁻¹ := by
              rw [pow_succ]

/-- A product is trivial modulo the relators exactly when its first factor equals the inverse of the second. -/
theorem mul_eq_one_iff_eq_inv :
    RelatorEquivalent R (u * v) 1 ↔ RelatorEquivalent R u v⁻¹ := by
  constructor
  · intro h
    simpa only [RelatorEquivalent, inv_inv, inv_one, mul_one] using h
  · intro h
    simpa only [RelatorEquivalent, inv_inv, inv_one, mul_one] using h

/--
If a product is relator-equivalent to one, the left factor is relator-equivalent to the inverse
of the right factor.
-/
theorem eq_inv_of_mul_eq_one (h : RelatorEquivalent R (u * v) 1) :
    RelatorEquivalent R u v⁻¹ :=
  mul_eq_one_iff_eq_inv.1 h

/--
A product is relator-equivalent to the identity when one factor is relator-equivalent to the
inverse of the other.
-/
theorem mul_eq_one_of_eq_inv (h : RelatorEquivalent R u v⁻¹) :
    RelatorEquivalent R (u * v) 1 :=
  mul_eq_one_iff_eq_inv.2 h

/--
If a left product is relator-equivalent to one and the left factor is trivial, the right factor
is relator-equivalent to one.
-/
theorem eq_one_of_mul_eq_one_left
    (hu : RelatorEquivalent R u 1)
    (huv : RelatorEquivalent R (u * v) 1) :
    RelatorEquivalent R v 1 := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at hu huv ⊢
  calc
    (v : G ⧸ Subgroup.normalClosure R) =
        (1 : G ⧸ Subgroup.normalClosure R) * v := by simp only [one_mul]
    _ = (u : G ⧸ Subgroup.normalClosure R) * v := by
      simpa using congrArg
        (fun z : G ⧸ Subgroup.normalClosure R =>
          z * (v : G ⧸ Subgroup.normalClosure R)) hu.symm
    _ = ((u * v : G) : G ⧸ Subgroup.normalClosure R) := rfl
    _ = 1 := huv

/--
If a right product is relator-equivalent to one and the right factor is trivial, the left factor
is relator-equivalent to one.
-/
theorem eq_one_of_mul_eq_one_right
    (huv : RelatorEquivalent R (u * v) 1)
    (hv : RelatorEquivalent R v 1) :
    RelatorEquivalent R u 1 := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at huv hv ⊢
  calc
    (u : G ⧸ Subgroup.normalClosure R) =
        (u : G ⧸ Subgroup.normalClosure R) * 1 := by simp only [mul_one]
    _ = (u : G ⧸ Subgroup.normalClosure R) * v := by
      simpa using congrArg
        (fun z : G ⧸ Subgroup.normalClosure R =>
          (u : G ⧸ Subgroup.normalClosure R) * z) hv.symm
    _ = ((u * v : G) : G ⧸ Subgroup.normalClosure R) := rfl
    _ = 1 := huv

/-- Left multiplication by the same word preserves relator equivalence. -/
theorem mul_left (h : RelatorEquivalent R u v) (a : G) : RelatorEquivalent R (a * u) (a * v) :=
  mul (refl R a) h

/-- Right multiplication by the same word preserves relator equivalence. -/
theorem mul_right (h : RelatorEquivalent R u v) (a : G) : RelatorEquivalent R (u * a) (v * a) :=
  mul h (refl R a)

/-- Replace a subword inside a two-sided context. -/
theorem context (h : RelatorEquivalent R u v) (a b : G) :
    RelatorEquivalent R (a * u * b) (a * v * b) :=
  mul_right (mul_left h a) b

/-- Conjugating both sides preserves relator equivalence. -/
theorem conj (h : RelatorEquivalent R u v) (a : G) :
    RelatorEquivalent R (a * u * a⁻¹) (a * v * a⁻¹) :=
  context h a a⁻¹

/--
If a word is relator-equivalent to the identity, then every conjugate of it is also
relator-equivalent to the identity.
-/
theorem conj_eq_one (h : RelatorEquivalent R u 1) (a : G) :
    RelatorEquivalent R (a * u * a⁻¹) 1 := by
  simpa using conj h a

/--
If a power is relator-equivalent to the identity, then every conjugate of that power is also
relator-equivalent to the identity.
-/
theorem conj_pow_eq_one
    {n : ℕ} (h : RelatorEquivalent R (u ^ n) 1) (a : G) :
    RelatorEquivalent R ((a * u * a⁻¹) ^ n) 1 := by
  simpa [conjugate_pow_eq] using conj_eq_one h a

/-- Every defining relator is equivalent to the identity. -/
theorem of_mem (hr : r ∈ R) : RelatorEquivalent R r 1 := by
  simpa [RelatorEquivalent] using (Subgroup.subset_normalClosure hr :
    r ∈ Subgroup.normalClosure R)

/-- Membership in the normal closure gives relator equivalence to the identity. -/
theorem of_mem_normalClosure (hr : r ∈ Subgroup.normalClosure R) :
    RelatorEquivalent R r 1 := by
  simpa [RelatorEquivalent] using hr

/-- Relator equivalence is monotone with respect to enlarging the relator family. -/
theorem mono (hR_to_S : R ⊆ S) (h : RelatorEquivalent R u v) :
    RelatorEquivalent S u v := by
  have hx : u * v⁻¹ ∈ Subgroup.normalClosure S :=
    Subgroup.normalClosure_mono hR_to_S
      (by simpa [RelatorEquivalent] using h)
  simpa [RelatorEquivalent] using hx

/-- Relator equivalence is monotone under an indexed union of relator families. -/
theorem mono_iUnion {ι : Sort*} (R : ι → Set G)
    (i : ι) (h : RelatorEquivalent (R i) u v) :
    RelatorEquivalent (Set.iUnion R) u v :=
  mono (R := R i) (S := Set.iUnion R)
    (fun _ hx => Set.mem_iUnion.2 ⟨i, hx⟩) h

/-- Relator equivalence is monotone under a doubly indexed union of relator families. -/
theorem mono_iUnion₂ {ι : Sort*} {κ : ι → Sort*}
    (R : ∀ i : ι, κ i → Set G)
    (i : ι) (j : κ i) (h : RelatorEquivalent (R i j) u v) :
    RelatorEquivalent (Set.iUnion fun i : ι => Set.iUnion (R i)) u v :=
  mono (R := R i j) (S := Set.iUnion fun i : ι => Set.iUnion (R i))
    (fun _ hx => Set.mem_iUnion.2 ⟨i, Set.mem_iUnion.2 ⟨j, hx⟩⟩) h

/-- A relator-equivalence certificate to the identity gives membership in the normal closure. -/
theorem mem_normalClosure_of_eq_one (h : RelatorEquivalent R r 1) :
    r ∈ Subgroup.normalClosure R := by
  simpa [RelatorEquivalent] using h

/--
If two words are relator-equivalent, then multiplying one by the inverse of the other gives an
element of the relator normal closure.
-/
theorem mul_inv_mem_normalClosure (h : RelatorEquivalent R u v) :
    u * v⁻¹ ∈ Subgroup.normalClosure R := by
  simpa [RelatorEquivalent] using h

/--
If two words are relator-equivalent, then their quotient lies in the normal closure of the
relators.
-/
theorem div_mem_normalClosure (h : RelatorEquivalent R u v) :
    u / v ∈ Subgroup.normalClosure R := by
  simpa [div_eq_mul_inv] using h.mul_inv_mem_normalClosure

/--
Multiplying a word by the inverse of a relator-equivalent word gives a word relator-equivalent
to one.
-/
theorem mul_inv_eq_one (h : RelatorEquivalent R u v) :
    RelatorEquivalent R (u * v⁻¹) 1 :=
  of_mem_normalClosure h.mul_inv_mem_normalClosure

/--
A quotient word is relator-equivalent to the identity when its numerator and denominator are
relator-equivalent to each other.
-/
theorem div_eq_one (h : RelatorEquivalent R u v) :
    RelatorEquivalent R (u / v) 1 := by
  simpa [div_eq_mul_inv] using h.mul_inv_eq_one

/-- The identity is equivalent to every defining relator. -/
theorem one_eq_of_mem_inv (hr : r ∈ R) : RelatorEquivalent R 1 r :=
  (of_mem hr).symm

end RelatorEquivalent

end ReidemeisterSchreier.Discrete.Presentations
