import ProCGroups.Cohomology.ContinuousMapFiniteStage
import ProCGroups.Cohomology.FiniteInvariantCharacter
import ProCGroups.Cohomology.FreeProPProjective
import ProCGroups.Cohomology.InvariantCharacterFiniteFamily
import ProCGroups.Cohomology.InvariantCharacterFiniteStage
import ProCGroups.Cohomology.RelativeNakayama

set_option autoImplicit false

/-!
# Pro-C group cohomology foundations

Canonical aggregate generated by the reviewed rehome.
-/
