/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ProCGroups.Cohomology.ContinuousMapFiniteStage
import ProCGroups.Cohomology.FiniteInvariantCharacter
import ProCGroups.Cohomology.FreeProPProjective
import ProCGroups.Cohomology.InvariantCharacterFiniteFamily
import ProCGroups.Cohomology.InvariantCharacterFiniteStage
import ProCGroups.Cohomology.RelativeNakayama

set_option autoImplicit false

/-!
# Pro-C group cohomology foundations

Canonical aggregate generated by the reviewed rehome.
-/
