import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.ElementarySplitCriterion
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.RegularWreathKernel
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.ElementaryFaithfulEmbeddingSolution
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.ResidualFiniteInvariantQuotient
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.ResidualSelfCentralizingImage
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.ResidualSelfCentralizingQuotient
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaEmbeddingSolutions
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaEmbeddingFormulation
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaPrimeOrderTest
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaOrdinary
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaMaximalQuotient
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaOpenSubgroup
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaProGroup
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaAllPrimes
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaFaithful
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.EmbeddingFormulation
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.Faithful
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.FaithfulKernel
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.PrimeOrderTest
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SlimnessAndTorsion
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaProPNormal
import ProCGroups.FiniteStepSolvableQuotients.AbelianActions.SigmaAbelianNormalObstruction

set_option autoImplicit false

/-!
# Abelianization actions

This aggregate module exposes faithfulness properties of conjugation actions on topological
abelianizations and their consequences for slimness and torsion.
-/
