/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ProCGroups.FreeProducts.UniversalProperty

set_option autoImplicit false

/-!
# Finite generating data

This file records concrete finite generating maps and finite families of
subgroups.  The companion bounds concatenate those maps to obtain explicit
generating families for the ambient group.
-/

noncomputable section

universe u

namespace ProCGroups.FreeConstructions

/-- The group is generated by at most \(r\) elements, expressed by an actual generating map. -/
def AbstractGeneratorRankLE (G : Type u) [Group G] (r : Nat) : Prop :=
  ∃ gen : Fin r → G, Subgroup.closure (Set.range gen) = ⊤

end ProCGroups.FreeConstructions
