import ProCGroups.GolodShafarevich.FiniteCriterion
import ProCGroups.GolodShafarevich.FiniteDimensions
import ProCGroups.GolodShafarevich.GeneratorGap
import ProCGroups.GolodShafarevich.GradedPieces
import ProCGroups.GolodShafarevich.NumericalCriterion
import ProCGroups.GolodShafarevich.TruncatedFoxMaps
import ProCGroups.GolodShafarevich.TruncatedFoxSequence
import ProCGroups.GolodShafarevich.TruncatedInequality

set_option autoImplicit false

/-!
# Golod--Shafarevich theory for pro-p groups

Reader-facing facade for the truncated Fox inequality and strict finite
generator/relation-rank bound.
-/



/-!
# Golod--Shafarevich theory

Canonical aggregate generated by the reviewed rehome.
-/
