/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ProCGroups.GolodShafarevich.CountableRelatorTarget
import ProCGroups.GolodShafarevich.CountableRelators
import ProCGroups.GolodShafarevich.WeightedFiniteCriterion
import ProCGroups.GolodShafarevich.FiniteCriterion
import ProCGroups.GolodShafarevich.FiniteDimensions
import ProCGroups.GolodShafarevich.GeneratorGap
import ProCGroups.GolodShafarevich.GradedPieces
import ProCGroups.GolodShafarevich.NumericalCriterion
import ProCGroups.GolodShafarevich.TruncatedFoxMaps
import ProCGroups.GolodShafarevich.TruncatedFoxSequence
import ProCGroups.GolodShafarevich.TruncatedInequality

set_option autoImplicit false

/-!
# Golod--Shafarevich theory for pro-p groups

Reader-facing facade for the truncated Fox inequality and strict finite
generator/relation-rank bound.
-/



/-!
# Golod--Shafarevich theory

Canonical aggregate generated by the reviewed rehome.
-/
