import Mathlib.Algebra.Category.Grp.Basic
import Mathlib.CategoryTheory.Limits.Shapes.Pullback.IsPullback.Defs
import Mathlib.GroupTheory.Coprod.Basic
import ProCGroups.Profinite.Basic
import ProCGroups.Topologies.ContinuousMulEquiv

/-!
# Pro C Groups / Categorical / Pushout Squares

This module constructs algebraic group pushouts from free products and normal
closures, and develops algebraic and profinite-tested pushout universal properties.
-/

namespace ProCGroups.Categorical

open CategoryTheory Limits
open scoped Monoid.Coprod

universe u v

section

variable {G G' H H₁ H₂ : Type u}
variable [Group G] [Group G'] [Group H] [Group H₁] [Group H₂]

/-- The abstract free product used as the carrier before imposing pushout relations. -/
abbrev PushoutFreeProduct (H₁ H₂ : Type u) [Group H₁] [Group H₂] :=
  Monoid.Coprod H₁ H₂

/-- The relators identifying the two legs of a group cospan inside the free product. -/
def pushoutRelators (β₁ : H →* H₁) (β₂ : H →* H₂) :
    Set (PushoutFreeProduct H₁ H₂) :=
  {z | ∃ h : H,
    z = (Monoid.Coprod.inl (β₁ h) : PushoutFreeProduct H₁ H₂)⁻¹ *
      (Monoid.Coprod.inr (β₂ h) : PushoutFreeProduct H₁ H₂)}

/-- The normal subgroup generated by the cospan-identifying relators. -/
def pushoutNormalClosure (β₁ : H →* H₁) (β₂ : H →* H₂) :
    Subgroup (PushoutFreeProduct H₁ H₂) :=
  Subgroup.normalClosure (pushoutRelators β₁ β₂)

/-- The relator closure used in the concrete pushout is normal. -/
instance pushoutNormalClosure_normal (β₁ : H →* H₁) (β₂ : H →* H₂) :
    (pushoutNormalClosure β₁ β₂).Normal :=
  Subgroup.normalClosure_normal

namespace AlgebraicPushout

/--
Algebraic group pushout carrier: the free product modulo the normal closure of
\(\operatorname{inl}(\beta_1 h)^{-1} * \operatorname{inr}(\beta_2 h)\).
-/
abbrev Carrier (β₁ : H →* H₁) (β₂ : H →* H₂) :=
  PushoutFreeProduct H₁ H₂ ⧸ pushoutNormalClosure β₁ β₂

/-- The left structural map into the algebraic pushout. -/
def inl (β₁ : H →* H₁) (β₂ : H →* H₂) :
    H₁ →* Carrier β₁ β₂ :=
  (QuotientGroup.mk' (pushoutNormalClosure β₁ β₂)).comp Monoid.Coprod.inl

/-- The right structural map into the algebraic pushout. -/
def inr (β₁ : H →* H₁) (β₂ : H →* H₂) :
    H₂ →* Carrier β₁ β₂ :=
  (QuotientGroup.mk' (pushoutNormalClosure β₁ β₂)).comp Monoid.Coprod.inr

/-- The algebraic pushout maps coequalize the original cospan. -/
theorem inl_comp_eq_inr_comp
    (β₁ : H →* H₁) (β₂ : H →* H₂) :
    (inl β₁ β₂).comp β₁ = (inr β₁ β₂).comp β₂ := by
  ext h
  change QuotientGroup.mk' (pushoutNormalClosure β₁ β₂)
      (Monoid.Coprod.inl (β₁ h) : PushoutFreeProduct H₁ H₂) =
    QuotientGroup.mk' (pushoutNormalClosure β₁ β₂)
      (Monoid.Coprod.inr (β₂ h) : PushoutFreeProduct H₁ H₂)
  apply QuotientGroup.eq.2
  exact Subgroup.subset_normalClosure ⟨h, rfl⟩

/--
The concrete pushout descent map is characterized by its compatibility with the two canonical
inclusions.
-/
noncomputable def concretePushoutDesc
    (β₁ : H →* H₁) (β₂ : H →* H₂)
    {K : Type u} [Group K]
    (φ₁ : H₁ →* K) (φ₂ : H₂ →* K)
    (hφ : φ₁.comp β₁ = φ₂.comp β₂) :
    Carrier β₁ β₂ →* K :=
  let F : PushoutFreeProduct H₁ H₂ →* K := Monoid.Coprod.lift φ₁ φ₂
  QuotientGroup.lift (pushoutNormalClosure β₁ β₂) F <| by
    refine Subgroup.normalClosure_le_normal ?_
    rintro z ⟨h, rfl⟩
    change F ((Monoid.Coprod.inl (β₁ h) : PushoutFreeProduct H₁ H₂)⁻¹ *
        (Monoid.Coprod.inr (β₂ h) : PushoutFreeProduct H₁ H₂)) = 1
    rw [map_mul, map_inv]
    have hleft :
        F (Monoid.Coprod.inl (β₁ h) : PushoutFreeProduct H₁ H₂) = φ₁ (β₁ h) :=
      DFunLike.congr_fun (Monoid.Coprod.lift_comp_inl φ₁ φ₂) (β₁ h)
    have hright :
        F (Monoid.Coprod.inr (β₂ h) : PushoutFreeProduct H₁ H₂) = φ₂ (β₂ h) :=
      DFunLike.congr_fun (Monoid.Coprod.lift_comp_inr φ₁ φ₂) (β₂ h)
    have hcomp : φ₁ (β₁ h) = φ₂ (β₂ h) := DFunLike.congr_fun hφ h
    rw [hleft, hright, hcomp]
    simp only [inv_mul_cancel]

/-- The concrete pushout descent map is compatible with the left inclusion. -/
@[simp 900] theorem concretePushoutDesc_inl
    (β₁ : H →* H₁) (β₂ : H →* H₂)
    {K : Type u} [Group K]
    (φ₁ : H₁ →* K) (φ₂ : H₂ →* K)
    (hφ : φ₁.comp β₁ = φ₂.comp β₂) :
    (concretePushoutDesc β₁ β₂ φ₁ φ₂ hφ).comp (inl β₁ β₂) = φ₁ := by
  ext x
  change concretePushoutDesc β₁ β₂ φ₁ φ₂ hφ
      (QuotientGroup.mk' (pushoutNormalClosure β₁ β₂)
        (Monoid.Coprod.inl x : PushoutFreeProduct H₁ H₂)) = φ₁ x
  simp only [concretePushoutDesc, QuotientGroup.mk'_apply, QuotientGroup.lift_mk,
      Monoid.Coprod.lift_apply_inl]

/-- The concrete pushout descent map is compatible with the right inclusion. -/
@[simp 900] theorem concretePushoutDesc_inr
    (β₁ : H →* H₁) (β₂ : H →* H₂)
    {K : Type u} [Group K]
    (φ₁ : H₁ →* K) (φ₂ : H₂ →* K)
    (hφ : φ₁.comp β₁ = φ₂.comp β₂) :
    (concretePushoutDesc β₁ β₂ φ₁ φ₂ hφ).comp (inr β₁ β₂) = φ₂ := by
  ext x
  change concretePushoutDesc β₁ β₂ φ₁ φ₂ hφ
      (QuotientGroup.mk' (pushoutNormalClosure β₁ β₂)
        (Monoid.Coprod.inr x : PushoutFreeProduct H₁ H₂)) = φ₂ x
  simp only [concretePushoutDesc, QuotientGroup.mk'_apply, QuotientGroup.lift_mk,
      Monoid.Coprod.lift_apply_inr]

end AlgebraicPushout

/-- The concrete free-product quotient is a pushout in mathlib's category of groups. -/
theorem AlgebraicPushout.isPushout (β₁ : H →* H₁) (β₂ : H →* H₂) :
    CategoryTheory.IsPushout
      (GrpCat.ofHom β₁) (GrpCat.ofHom β₂)
      (GrpCat.ofHom (AlgebraicPushout.inl β₁ β₂))
      (GrpCat.ofHom (AlgebraicPushout.inr β₁ β₂)) := by
  let condition :
      GrpCat.ofHom β₁ ≫ GrpCat.ofHom (AlgebraicPushout.inl β₁ β₂) =
        GrpCat.ofHom β₂ ≫ GrpCat.ofHom (AlgebraicPushout.inr β₁ β₂) :=
    GrpCat.hom_ext (AlgebraicPushout.inl_comp_eq_inr_comp β₁ β₂)
  refine { w := condition, isColimit' := ⟨?_⟩ }
  refine PushoutCocone.IsColimit.mk condition ?_ ?_ ?_ ?_
  · intro s
    exact GrpCat.ofHom <|
      AlgebraicPushout.concretePushoutDesc β₁ β₂ s.inl.hom s.inr.hom
        (congrArg GrpCat.Hom.hom s.condition)
  · intro s
    apply GrpCat.hom_ext
    exact AlgebraicPushout.concretePushoutDesc_inl β₁ β₂ s.inl.hom s.inr.hom
      (congrArg GrpCat.Hom.hom s.condition)
  · intro s
    apply GrpCat.hom_ext
    exact AlgebraicPushout.concretePushoutDesc_inr β₁ β₂ s.inl.hom s.inr.hom
      (congrArg GrpCat.Hom.hom s.condition)
  · intro s m hm1 hm2
    apply GrpCat.hom_ext
    let q : PushoutFreeProduct H₁ H₂ →* AlgebraicPushout.Carrier β₁ β₂ :=
      QuotientGroup.mk' (pushoutNormalClosure β₁ β₂)
    let F : PushoutFreeProduct H₁ H₂ →* s.pt :=
      Monoid.Coprod.lift s.inl.hom s.inr.hom
    have hmq : m.hom.comp q = F := by
      apply Monoid.Coprod.hom_ext
      · calc
          (m.hom.comp q).comp Monoid.Coprod.inl =
              m.hom.comp (AlgebraicPushout.inl β₁ β₂) := rfl
          _ = s.inl.hom := congrArg GrpCat.Hom.hom hm1
          _ = F.comp Monoid.Coprod.inl :=
            (Monoid.Coprod.lift_comp_inl s.inl.hom s.inr.hom).symm
      · calc
          (m.hom.comp q).comp Monoid.Coprod.inr =
              m.hom.comp (AlgebraicPushout.inr β₁ β₂) := rfl
          _ = s.inr.hom := congrArg GrpCat.Hom.hom hm2
          _ = F.comp Monoid.Coprod.inr :=
            (Monoid.Coprod.lift_comp_inr s.inl.hom s.inr.hom).symm
    have hdescq :
        (AlgebraicPushout.concretePushoutDesc β₁ β₂ s.inl.hom s.inr.hom
          (congrArg GrpCat.Hom.hom s.condition)).comp q = F := by
      apply Monoid.Coprod.hom_ext
      · calc
          ((AlgebraicPushout.concretePushoutDesc β₁ β₂ s.inl.hom s.inr.hom
              (congrArg GrpCat.Hom.hom s.condition)).comp q).comp
                Monoid.Coprod.inl =
            (AlgebraicPushout.concretePushoutDesc β₁ β₂ s.inl.hom s.inr.hom
              (congrArg GrpCat.Hom.hom s.condition)).comp
                (AlgebraicPushout.inl β₁ β₂) := rfl
          _ = s.inl.hom :=
            AlgebraicPushout.concretePushoutDesc_inl β₁ β₂ s.inl.hom s.inr.hom
              (congrArg GrpCat.Hom.hom s.condition)
          _ = F.comp Monoid.Coprod.inl :=
            (Monoid.Coprod.lift_comp_inl s.inl.hom s.inr.hom).symm
      · calc
          ((AlgebraicPushout.concretePushoutDesc β₁ β₂ s.inl.hom s.inr.hom
              (congrArg GrpCat.Hom.hom s.condition)).comp q).comp
                Monoid.Coprod.inr =
            (AlgebraicPushout.concretePushoutDesc β₁ β₂ s.inl.hom s.inr.hom
              (congrArg GrpCat.Hom.hom s.condition)).comp
                (AlgebraicPushout.inr β₁ β₂) := rfl
          _ = s.inr.hom :=
            AlgebraicPushout.concretePushoutDesc_inr β₁ β₂ s.inl.hom s.inr.hom
              (congrArg GrpCat.Hom.hom s.condition)
          _ = F.comp Monoid.Coprod.inr :=
            (Monoid.Coprod.lift_comp_inr s.inl.hom s.inr.hom).symm
    apply MonoidHom.ext
    intro y
    rcases QuotientGroup.mk'_surjective
      (pushoutNormalClosure β₁ β₂) y with ⟨z, rfl⟩
    exact congrArg (fun f : PushoutFreeProduct H₁ H₂ →* s.pt => f z)
      (hmq.trans hdescq.symm)
end

section

variable {G G' H H₁ H₂ : Type u}
variable [Group G] [Group G'] [Group H] [Group H₁] [Group H₂]
variable [TopologicalSpace G] [TopologicalSpace G'] [TopologicalSpace H]
variable [TopologicalSpace H₁] [TopologicalSpace H₂]
variable [IsTopologicalGroup G] [IsTopologicalGroup G'] [IsTopologicalGroup H]
variable [IsTopologicalGroup H₁] [IsTopologicalGroup H₂]
variable [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]
variable [CompactSpace G'] [T2Space G'] [TotallyDisconnectedSpace G']


/-- Continuous pushout property tested by profinite target objects.

This definition does not assert that the four objects in the square are themselves profinite. -/
def HasProfiniteTestPushoutProperty (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (α₁ : H₁ →ₜ* G) (α₂ : H₂ →ₜ* G) : Prop :=
  α₁.comp β₁ = α₂.comp β₂ ∧
    ∀ ⦃K : Type u⦄ [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
      [CompactSpace K] [T2Space K] [TotallyDisconnectedSpace K],
      ∀ (φ₁ : H₁ →ₜ* K) (φ₂ : H₂ →ₜ* K),
      φ₁.comp β₁ = φ₂.comp β₂ →
      ∃! φ : G →ₜ* K, φ.comp α₁ = φ₁ ∧ φ.comp α₂ = φ₂

/-- Chosen continuous morphism induced by the profinite pushout universal property. -/
noncomputable def pushoutDescCont
    {β₁ : H →ₜ* H₁} {β₂ : H →ₜ* H₂}
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {K : Type u} [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
    [CompactSpace K] [T2Space K] [TotallyDisconnectedSpace K]
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (φ₁ : H₁ →ₜ* K) (φ₂ : H₂ →ₜ* K)
    (hφ : φ₁.comp β₁ = φ₂.comp β₂) : G →ₜ* K :=
  Classical.choose (ExistsUnique.exists (hpo.2 (K := K) φ₁ φ₂ hφ))

omit [IsTopologicalGroup G] [IsTopologicalGroup H]
    [IsTopologicalGroup H₁] [IsTopologicalGroup H₂]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Specification of the chosen continuous pushout descent map. -/
theorem pushoutDescCont_spec
    {β₁ : H →ₜ* H₁} {β₂ : H →ₜ* H₂}
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {K : Type u} [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
    [CompactSpace K] [T2Space K] [TotallyDisconnectedSpace K]
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (φ₁ : H₁ →ₜ* K) (φ₂ : H₂ →ₜ* K)
    (hφ : φ₁.comp β₁ = φ₂.comp β₂) :
    (pushoutDescCont hpo φ₁ φ₂ hφ).comp α₁ = φ₁ ∧
      (pushoutDescCont hpo φ₁ φ₂ hφ).comp α₂ = φ₂ :=
  Classical.choose_spec (ExistsUnique.exists (hpo.2 (K := K) φ₁ φ₂ hφ))

omit [IsTopologicalGroup G] [IsTopologicalGroup H]
    [IsTopologicalGroup H₁] [IsTopologicalGroup H₂]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Left composite of the chosen continuous pushout descent map.
-/
@[simp] theorem pushoutDescCont_left
    {β₁ : H →ₜ* H₁} {β₂ : H →ₜ* H₂}
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {K : Type u} [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
    [CompactSpace K] [T2Space K] [TotallyDisconnectedSpace K]
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (φ₁ : H₁ →ₜ* K) (φ₂ : H₂ →ₜ* K)
    (hφ : φ₁.comp β₁ = φ₂.comp β₂) :
    (pushoutDescCont hpo φ₁ φ₂ hφ).comp α₁ = φ₁ :=
  (pushoutDescCont_spec hpo φ₁ φ₂ hφ).1

omit [IsTopologicalGroup G] [IsTopologicalGroup H]
    [IsTopologicalGroup H₁] [IsTopologicalGroup H₂]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Right composite of the chosen continuous pushout descent map.
-/
@[simp] theorem pushoutDescCont_right
    {β₁ : H →ₜ* H₁} {β₂ : H →ₜ* H₂}
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {K : Type u} [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
    [CompactSpace K] [T2Space K] [TotallyDisconnectedSpace K]
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (φ₁ : H₁ →ₜ* K) (φ₂ : H₂ →ₜ* K)
    (hφ : φ₁.comp β₁ = φ₂.comp β₂) :
    (pushoutDescCont hpo φ₁ φ₂ hφ).comp α₂ = φ₂ :=
  (pushoutDescCont_spec hpo φ₁ φ₂ hφ).2

omit [IsTopologicalGroup G] [IsTopologicalGroup H]
    [IsTopologicalGroup H₁] [IsTopologicalGroup H₂]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Uniqueness of the chosen continuous pushout descent map. -/
theorem pushoutDescCont_uniq
    {β₁ : H →ₜ* H₁} {β₂ : H →ₜ* H₂}
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {K : Type u} [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
    [CompactSpace K] [T2Space K] [TotallyDisconnectedSpace K]
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (φ₁ : H₁ →ₜ* K) (φ₂ : H₂ →ₜ* K)
    (hφ : φ₁.comp β₁ = φ₂.comp β₂)
    {ψ : G →ₜ* K}
    (hψ : ψ.comp α₁ = φ₁ ∧ ψ.comp α₂ = φ₂) :
    ψ = pushoutDescCont hpo φ₁ φ₂ hφ :=
  (hpo.2 (K := K) φ₁ φ₂ hφ).unique hψ
    (pushoutDescCont_spec hpo φ₁ φ₂ hφ)

omit [IsTopologicalGroup H] [IsTopologicalGroup H₁] [IsTopologicalGroup H₂] in
/-- The distinguished map from a profinite pushout object to itself is the identity. -/
@[simp 900] theorem pushoutDescCont_self
    {β₁ : H →ₜ* H₁} {β₂ : H →ₜ* H₂}
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    : pushoutDescCont hpo α₁ α₂ hpo.1 = ContinuousMonoidHom.id G := by
  symm
  exact
    pushoutDescCont_uniq (K := G) hpo α₁ α₂ hpo.1
      (ψ := ContinuousMonoidHom.id G) ⟨rfl, rfl⟩

omit [IsTopologicalGroup G] [IsTopologicalGroup H]
    [IsTopologicalGroup H₁] [IsTopologicalGroup H₂]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Extensionality of continuous morphisms out of a profinite pushout object. -/
theorem pushoutCont_hom_ext
    {β₁ : H →ₜ* H₁} {β₂ : H →ₜ* H₂}
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {K : Type u} [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
    [CompactSpace K] [T2Space K] [TotallyDisconnectedSpace K]
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    {ψ ψ' : G →ₜ* K}
    (h₁ : ψ.comp α₁ = ψ'.comp α₁)
    (h₂ : ψ.comp α₂ = ψ'.comp α₂) :
    ψ = ψ' := by
  have hφ : (ψ.comp α₁).comp β₁ = (ψ.comp α₂).comp β₂ := by
    ext x
    exact congrArg ψ (DFunLike.congr_fun hpo.1 x)
  have hψ :
      ψ = pushoutDescCont hpo (ψ.comp α₁) (ψ.comp α₂) hφ := by
    exact pushoutDescCont_uniq hpo (ψ.comp α₁) (ψ.comp α₂) hφ (ψ := ψ) ⟨rfl, rfl⟩
  have hψ' :
      ψ' = pushoutDescCont hpo (ψ.comp α₁) (ψ.comp α₂) hφ := by
    exact pushoutDescCont_uniq hpo (ψ.comp α₁) (ψ.comp α₂) hφ
      (ψ := ψ') ⟨h₁.symm, h₂.symm⟩
  exact hψ.trans hψ'.symm

/-- Canonical comparison map between two profinite pushout objects of the same cospan.
-/
noncomputable def pushoutContMapOfIsPushout
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {α₁' : H₁ →ₜ* G'} {α₂' : H₂ →ₜ* G'}
    (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (hpo' : HasProfiniteTestPushoutProperty β₁ β₂ α₁' α₂')
    : G →ₜ* G' :=
  pushoutDescCont hpo α₁' α₂' hpo'.1

omit [IsTopologicalGroup H] [IsTopologicalGroup H₁] [IsTopologicalGroup H₂] in
/-- The canonical comparison map from a profinite pushout object to itself is the identity. -/
@[simp 900] theorem pushoutContMapOfIsPushout_self
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    : pushoutContMapOfIsPushout β₁ β₂ hpo hpo = ContinuousMonoidHom.id G := by
  change pushoutDescCont hpo α₁ α₂ hpo.1 = ContinuousMonoidHom.id G
  exact pushoutDescCont_self (hpo := hpo)

omit [IsTopologicalGroup G] [IsTopologicalGroup H]
    [IsTopologicalGroup H₁] [IsTopologicalGroup H₂]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Left composite of the canonical comparison map between profinite pushout objects.
-/
@[simp 900] theorem pushoutContMapOfIsPushout_left
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {α₁' : H₁ →ₜ* G'} {α₂' : H₂ →ₜ* G'}
    (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (hpo' : HasProfiniteTestPushoutProperty β₁ β₂ α₁' α₂')
    : (pushoutContMapOfIsPushout β₁ β₂ hpo hpo').comp α₁ = α₁' :=
  by
    change (pushoutDescCont hpo α₁' α₂' hpo'.1).comp α₁ = α₁'
    exact pushoutDescCont_left hpo α₁' α₂' hpo'.1

omit [IsTopologicalGroup G] [IsTopologicalGroup H]
    [IsTopologicalGroup H₁] [IsTopologicalGroup H₂]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Right composite of the canonical comparison map between profinite pushout objects.
-/
@[simp 900] theorem pushoutContMapOfIsPushout_right
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {α₁' : H₁ →ₜ* G'} {α₂' : H₂ →ₜ* G'}
    (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (hpo' : HasProfiniteTestPushoutProperty β₁ β₂ α₁' α₂')
    : (pushoutContMapOfIsPushout β₁ β₂ hpo hpo').comp α₂ = α₂' :=
  by
    change (pushoutDescCont hpo α₁' α₂' hpo'.1).comp α₂ = α₂'
    exact pushoutDescCont_right hpo α₁' α₂' hpo'.1


omit [IsTopologicalGroup H] [IsTopologicalGroup H₁] [IsTopologicalGroup H₂] in
/-- Any two profinite pushout objects of the same cospan are canonically bijective. -/
theorem bijective_pushoutContMapOfIsPushout
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {α₁' : H₁ →ₜ* G'} {α₂' : H₂ →ₜ* G'}
    (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (hpo' : HasProfiniteTestPushoutProperty β₁ β₂ α₁' α₂')
    : Function.Bijective (pushoutContMapOfIsPushout β₁ β₂ hpo hpo') := by
  let φ : G →ₜ* G' := pushoutContMapOfIsPushout β₁ β₂ hpo hpo'
  let ψ : G' →ₜ* G := pushoutContMapOfIsPushout β₁ β₂ hpo' hpo
  have hleft : ψ.comp φ = ContinuousMonoidHom.id G := by
    apply pushoutCont_hom_ext hpo
    · calc
        (ψ.comp φ).comp α₁ = ψ.comp (φ.comp α₁) := by rfl
        _ = ψ.comp α₁' := by rw [pushoutContMapOfIsPushout_left β₁ β₂ hpo hpo']
        _ = α₁ := pushoutContMapOfIsPushout_left β₁ β₂ hpo' hpo
    · calc
        (ψ.comp φ).comp α₂ = ψ.comp (φ.comp α₂) := by rfl
        _ = ψ.comp α₂' := by rw [pushoutContMapOfIsPushout_right β₁ β₂ hpo hpo']
        _ = α₂ := pushoutContMapOfIsPushout_right β₁ β₂ hpo' hpo
  have hright : φ.comp ψ = ContinuousMonoidHom.id G' := by
    apply pushoutCont_hom_ext hpo'
    · calc
        (φ.comp ψ).comp α₁' = φ.comp (ψ.comp α₁') := by rfl
        _ = φ.comp α₁ := by rw [pushoutContMapOfIsPushout_left β₁ β₂ hpo' hpo]
        _ = α₁' := pushoutContMapOfIsPushout_left β₁ β₂ hpo hpo'
    · calc
        (φ.comp ψ).comp α₂' = φ.comp (ψ.comp α₂') := by rfl
        _ = φ.comp α₂ := by rw [pushoutContMapOfIsPushout_right β₁ β₂ hpo' hpo]
        _ = α₂' := pushoutContMapOfIsPushout_right β₁ β₂ hpo hpo'
  refine ⟨?_, ?_⟩
  · intro x y hxy
    have hx : ψ (φ x) = x := by
      simpa [φ, ψ] using congrArg (fun f : G →ₜ* G => f x) hleft
    have hy : ψ (φ y) = y := by
      simpa [φ, ψ] using congrArg (fun f : G →ₜ* G => f y) hleft
    calc
      x = ψ (φ x) := hx.symm
      _ = ψ (φ y) := by simpa [φ] using congrArg ψ hxy
      _ = y := hy
  · intro y
    refine ⟨ψ y, ?_⟩
    simpa [φ, ψ] using congrArg (fun f : G' →ₜ* G' => f y) hright

/-- Canonical continuous multiplicative equivalence between two profinite pushout objects.
-/
noncomputable def pushoutContEquivOfIsPushout
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {α₁' : H₁ →ₜ* G'} {α₂' : H₂ →ₜ* G'}
    (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (hpo' : HasProfiniteTestPushoutProperty β₁ β₂ α₁' α₂')
    : G ≃ₜ* G' := by
  exact ContinuousMulEquiv.ofBijectiveCompactToT2
    (pushoutContMapOfIsPushout β₁ β₂ hpo hpo')
    (pushoutContMapOfIsPushout β₁ β₂ hpo hpo').continuous_toFun
    (bijective_pushoutContMapOfIsPushout β₁ β₂ hpo hpo')

omit [IsTopologicalGroup H] [IsTopologicalGroup H₁] [IsTopologicalGroup H₂] in
/-- Left composite of the canonical continuous pushout equivalence.
-/
@[simp] theorem pushoutContEquivOfIsPushout_left
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {α₁' : H₁ →ₜ* G'} {α₂' : H₂ →ₜ* G'}
    (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (hpo' : HasProfiniteTestPushoutProperty β₁ β₂ α₁' α₂')
    : ((pushoutContEquivOfIsPushout β₁ β₂ hpo hpo' : G →ₜ* G').comp α₁) = α₁' := by
  change (pushoutContMapOfIsPushout β₁ β₂ hpo hpo').comp α₁ = α₁'
  exact pushoutContMapOfIsPushout_left β₁ β₂ hpo hpo'

omit [IsTopologicalGroup H] [IsTopologicalGroup H₁] [IsTopologicalGroup H₂] in
/-- Right composite of the canonical continuous pushout equivalence.
-/
@[simp] theorem pushoutContEquivOfIsPushout_right
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {α₁' : H₁ →ₜ* G'} {α₂' : H₂ →ₜ* G'}
    (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (hpo' : HasProfiniteTestPushoutProperty β₁ β₂ α₁' α₂')
    : ((pushoutContEquivOfIsPushout β₁ β₂ hpo hpo' : G →ₜ* G').comp α₂) = α₂' := by
  change (pushoutContMapOfIsPushout β₁ β₂ hpo hpo').comp α₂ = α₂'
  exact pushoutContMapOfIsPushout_right β₁ β₂ hpo hpo'

omit [IsTopologicalGroup H] [IsTopologicalGroup H₁] [IsTopologicalGroup H₂] in
/-- Left-leg formula for the inverse profinite pushout comparison equivalence. -/
@[simp 900] theorem pushoutContEquivOfIsPushout_symm_left
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {α₁' : H₁ →ₜ* G'} {α₂' : H₂ →ₜ* G'}
    (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (hpo' : HasProfiniteTestPushoutProperty β₁ β₂ α₁' α₂')
    : (((pushoutContEquivOfIsPushout β₁ β₂ hpo hpo').symm : G' →ₜ* G).comp α₁') = α₁ := by
  ext x
  let e := pushoutContEquivOfIsPushout β₁ β₂ hpo hpo'
  exact e.injective <| by
    calc
      e ((((e.symm : G' →ₜ* G).comp α₁') x)) = α₁' x := by
        change e (e.symm (α₁' x)) = α₁' x
        simp only [ContinuousMulEquiv.apply_symm_apply]
      _ = e (α₁ x) := by
        have hleft :
            (pushoutContMapOfIsPushout β₁ β₂ hpo hpo').comp α₁ = α₁' :=
          pushoutContMapOfIsPushout_left β₁ β₂ hpo hpo'
        have hleft_apply :
            pushoutContMapOfIsPushout β₁ β₂ hpo hpo' (α₁ x) = α₁' x := by
          exact congrFun (congrArg (fun f : H₁ →ₜ* G' => (f : H₁ → G')) hleft) x
        change α₁' x = pushoutContMapOfIsPushout β₁ β₂ hpo hpo' (α₁ x)
        simpa using hleft_apply.symm

omit [IsTopologicalGroup H] [IsTopologicalGroup H₁] [IsTopologicalGroup H₂] in
/-- Right-leg formula for the inverse profinite pushout comparison equivalence. -/
@[simp 900] theorem pushoutContEquivOfIsPushout_symm_right
    {α₁ : H₁ →ₜ* G} {α₂ : H₂ →ₜ* G}
    {α₁' : H₁ →ₜ* G'} {α₂' : H₂ →ₜ* G'}
    (β₁ : H →ₜ* H₁) (β₂ : H →ₜ* H₂)
    (hpo : HasProfiniteTestPushoutProperty β₁ β₂ α₁ α₂)
    (hpo' : HasProfiniteTestPushoutProperty β₁ β₂ α₁' α₂')
    : (((pushoutContEquivOfIsPushout β₁ β₂ hpo hpo').symm : G' →ₜ* G).comp α₂') = α₂ := by
  ext x
  let e := pushoutContEquivOfIsPushout β₁ β₂ hpo hpo'
  exact e.injective <| by
    calc
      e ((((e.symm : G' →ₜ* G).comp α₂') x)) = α₂' x := by
        change e (e.symm (α₂' x)) = α₂' x
        simp only [ContinuousMulEquiv.apply_symm_apply]
      _ = e (α₂ x) := by
        have hright :
            (pushoutContMapOfIsPushout β₁ β₂ hpo hpo').comp α₂ = α₂' :=
          pushoutContMapOfIsPushout_right β₁ β₂ hpo hpo'
        have hright_apply :
            pushoutContMapOfIsPushout β₁ β₂ hpo hpo' (α₂ x) = α₂' x := by
          exact congrFun (congrArg (fun f : H₂ →ₜ* G' => (f : H₂ → G')) hright) x
        change α₂' x = pushoutContMapOfIsPushout β₁ β₂ hpo hpo' (α₂ x)
        simpa using hright_apply.symm

end


end ProCGroups.Categorical
