import ProCGroups.FreeProC.Characterization.EmbeddingProblems

/-!
# Pro C Groups / Free pro-C / Characterization / Quasifree

This module formulates quasifree proper-solution growth and its cardinal
monotonicity consequences.
-/

noncomputable section

open scoped Cardinal

namespace ProCGroups.FreeProC.Characterization

universe u

/-- A topological group has a topological generating set of cardinality \(\kappa\). -/
def HasTopologicalGeneratingSetOfCardinality
    (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (κ : Cardinal) : Prop :=
  ∃ S : Set G, Generation.TopologicallyGenerates (G := G) S ∧ Cardinal.mk S = κ

/--
A group has the quasifree proper-solution property at rank \(\kappa\) for finite split
\(C\)-embedding problems.
-/
def HasQuasifreeProperSolutionProperty
    (C : ProCGroups.FiniteGroupClass.{u})
    (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (κ : Cardinal) : Prop :=
  ∀ P : TopologicalEmbeddingProblem G,
    IsFiniteSplitCEmbeddingProblem C P → P.HasAtLeastProperSolutions κ

/--
Quasifreeness at infinite rank \(\kappa\). The rank field is deliberately topological: in
profinite contexts an abstract generating set is too weak and does not control the closed
subgroup generated by the chosen family. The lifting field records the standard proper-solution
condition for finite split embedding problems.
-/
def IsQuasifreeOfRank (C : ProCGroups.FiniteGroupClass.{u})
    (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]
    (κ : Cardinal) : Prop :=
  ProCGroups.ProC.HasOpenNormalBasisInClass C G ∧
    HasTopologicalGeneratingSetOfCardinality G κ ∧
      Cardinal.aleph0 ≤ κ ∧
        HasQuasifreeProperSolutionProperty C G κ

end ProCGroups.FreeProC.Characterization
